### ISSUE TITLE
Wrong weekdays in calendar

### ISSUE THREAD

**Issue by mphash** [GaspardMerten/date_range_picker#2]
In the first row, the week days are off by one. This is because the DateTime weekday has Monday as the first day, but the Intl.DateFormat days start with Sunday. This error is also present on the pub page:
![image](https://github.com/GaspardMerten/date_range_picker/assets/74971979/8ca456b1-ef9f-4540-a87c-7fdce8c23ecc)

**Comment by GaspardMerten** [comment]
^^; Oups...

I merged your PR into the main codebase. Thank you for taking the time!

I hope this package helps you with your project :).
